export const patients = [
  {
    id: "pac-001",
    name: "Agustín Franco",
    document: "32.884.102",
    phone: "+54 9 11 5842-1180",
    email: "agustin.franco@email.com",
    condition: "Lumbalgia",
    status: "Activo",
    progress: "Mejora funcional 68%",
    lastSession: "24 May",
    nextAppointment: "27 May, 09:00",
  },
  {
    id: "pac-002",
    name: "Camila Ríos",
    document: "38.210.443",
    phone: "+54 9 11 6120-4321",
    email: "camila.rios@email.com",
    condition: "Esguince de tobillo",
    status: "Activo",
    progress: "Fase de fortalecimiento",
    lastSession: "23 May",
    nextAppointment: "28 May, 10:30",
  },
  {
    id: "pac-003",
    name: "Pablo Torres",
    document: "29.742.551",
    phone: "+54 9 11 4922-9041",
    email: "pablo.torres@email.com",
    condition: "Hombro congelado",
    status: "Seguimiento",
    progress: "Movilidad en progreso",
    lastSession: "22 May",
    nextAppointment: "29 May, 12:00",
  },
  {
    id: "pac-004",
    name: "Marina Duarte",
    document: "35.124.980",
    phone: "+54 9 11 3488-7781",
    email: "marina.duarte@email.com",
    condition: "Rehabilitación de rodilla",
    status: "Activo",
    progress: "Marcha sin dolor",
    lastSession: "25 May",
    nextAppointment: "30 May, 09:30",
  },
  {
    id: "pac-005",
    name: "Laura Méndez",
    document: "31.551.620",
    phone: "+54 9 11 5021-9012",
    email: "laura.mendez@email.com",
    condition: "Cervicalgia",
    status: "Activo",
    progress: "Disminución de dolor",
    lastSession: "25 May",
    nextAppointment: "30 May, 10:30",
  },
];

export const appointments = [
  {
    id: "turno-001",
    date: "2026-05-27",
    time: "09:00",
    patient: "Marina Duarte",
    reason: "Rehabilitación de rodilla",
    status: "Confirmado",
    modality: "Presencial",
    duration: "45 min",
  },
  {
    id: "turno-002",
    date: "2026-05-27",
    time: "10:30",
    patient: "Laura Méndez",
    reason: "Cervicalgia",
    status: "Confirmado",
    modality: "Presencial",
    duration: "45 min",
  },
  {
    id: "turno-003",
    date: "2026-05-27",
    time: "12:00",
    patient: "Tomás Pereyra",
    reason: "Control postural",
    status: "Pendiente",
    modality: "Virtual",
    duration: "30 min",
  },
  {
    id: "turno-004",
    date: "2026-05-28",
    time: "11:15",
    patient: "Camila Ríos",
    reason: "Fortalecimiento tobillo",
    status: "Confirmado",
    modality: "Presencial",
    duration: "45 min",
  },
];

export const evolutions = [
  {
    id: "evo-001",
    patient: "Agustín Franco",
    date: "2026-05-24",
    diagnosis: "Lumbalgia",
    pain: "3/10",
    mobility: "Mejora en flexión lumbar",
    notes: "Tolera rutina de estabilidad central sin aumento de dolor.",
  },
  {
    id: "evo-002",
    patient: "Camila Ríos",
    date: "2026-05-23",
    diagnosis: "Esguince de tobillo",
    pain: "2/10",
    mobility: "Carga monopodal estable",
    notes: "Se incorpora trabajo propioceptivo con buena respuesta.",
  },
  {
    id: "evo-003",
    patient: "Laura Méndez",
    date: "2026-05-25",
    diagnosis: "Cervicalgia",
    pain: "4/10",
    mobility: "Rotación derecha limitada",
    notes: "Disminuye rigidez posterior luego de terapia manual.",
  },
];
